### ISSUE TITLE
extracting amino type names from sdk systematically

### ISSUE THREAD

**Issue by pyramation** [osmosis-labs/telescope#200]
```
Error: Multiple types are registered with Amino type identifier 'cosmos-sdk/MsgVote': '/cosmos.gov.v1beta1.MsgVote', '/cosmos.group.v1.MsgVote'. Thus fromAmino cannot be performed.
```

**Comment by pyramation** [comment]
Hey @webmaster128 it seems that in the cosmos sdk protos, there are three `cosmos-sdk/MsgVote` messages. This causes cosmjs to be upset because the registry has conflicts.

Some ideas to mitigate this:

- require the dev to specify which packages they want to include in their packages so their client is scoped to only what they choose
- allow the dev to create multiple signing clients that register different sets of amino/proto type messages in the registry

Currently I'm going to use the `prototypes.excludes.packages` option to exclude certain packages, which works for now to avoid the error.

**Comment by webmaster128** [comment]
This is not a conflict in the type name itself (which is nicely prefixed). It's a collision in the Amino interface identifier. Since this identifier is supposed to identify the message type, it must not be reused for multiple messages. So I would consider that an SDK bug.

**Comment by webmaster128** [comment]
> I guess I can't help but wonder, why don't proto type names == amino type names?

Because `cosmos-sdk/MsgVote`, `cosmos-sdk/MsgSend` and friends have been there pre-Stargate, long before protbuf was introduced. They are kept for Amino JSON signing compatibility.

> Seems that we have to hunt down any calls to legacy.RegisterAminoMsg and cdc.RegisterConcrete to find the name. There is no systematic way of generating these names from what it seems.

Yes, it has always been a matter of manually figuring out. Usually it was just `cosmos-sdk/<message name without namespace>`. This is the first time I see the same message name being used in different namespaces.

One think you can do is maintain a list of known exceptions that do not follow the `cosmos-sdk/<message name without namespace>` pattern and use the pattern for the rest.

**Comment by pyramation** [comment]
ok cool, so we just need to keep managing the exceptions. Telescope does have this, as well as defaults, so it is manageable. 

https://github.com/osmosis-labs/telescope#amino-encoding

- `aminoEncoding.exceptions`  to set specific aminoType name exceptions, [with defaults here](https://github.com/osmosis-labs/telescope/blob/main/packages/types/src/aminos.ts#L11-L16)

- `aminoEncoding.typeUrlToAmino` which allows devs to create functions for aminoType name exceptions programmatically if there happens to be some sort of dynamic way to calc (for osmosis this worked well)
